services:
  app:
    build: .  
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app  
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - DEPLOYMENT_NAME=${DEPLOYMENT_NAME}