services:
  ia_generativa_prometeu:
    build: .  
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app  
    environment:
      - OPENAI_API_TYPE=${OPENAI_API_TYPE}
      - OPENAI_ENDPOINT=${OPENAI_ENDPOINT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_VERSION=${OPENAI_API_VERSION}
      - DEPLOYMENT_NAME=${DEPLOYMENT_NAME}
